version: '3.3'
services:
  nginx:
    image: nginx:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/